### ISSUE TITLE
Issue getting prefix from GroupManager

### ISSUE THREAD

**Issue by autrilla** [MyEssentials/MyTown#13]
Whenever I try to use the chat on my server (MCPC+, 1.5.2, latest MyTown), I get disconnected (genericReason). I did a bit of research and this is because it fails to get the prefix. I have MyTown, MyTownLib, ForgePermsWithoutPEX and ForgePermsCBBridge. What could be the issue? (the getPrefix() method returns null).

**Comment by Torins** [comment]
I'll look into it probably tomorrow. Never used mytown together with GroupManager before.

Can you by any chance supply me configs for GroupManager so I don't have to look up how to make groups and permissions in there? :)

**Comment by autrilla** [comment]
Alright. I'm using the default configs.

**Comment by autrilla** [comment]
By the way, if you fix this, it'd be great if you could give me a 1.5.2 fix too :)

**Comment by autrilla** [comment]
Happens with bPermissions too. Happens mostly with anything.

**Comment by McyD** [comment]
I don't get disconnected with Groupmanager on 1.5.2 but it is definitely not pulling the prefix's.  Here is a copy of my GroupManager Perms if it helps at all https://www.dropbox.com/s/rkhjg30neg2t3ya/groups.yml.   They are completely customized form the default btw.

**Comment by KaesBuerschtl** [comment]
Since this is still open; I experienced a similar issue using MyTown-1.5.1.11, ForgePermsCBBridge-1.1.12, latest MCPC+ and PEX(Bukkit ver.) for MC1.5.2. The cause was setting S:TextColoringPrefix=& and not putting quotes around the prefix in the permissions.yml during testing. Adding quotes fixes the disconnect on chat, but it still doesn't read/display the prefix.

**Comment by jgoett154** [comment]
Prefixes should be working in the latest and should not cause anymore issues.
