### ISSUE TITLE
[1.5.1.8] Permissions not being properly evaluated

### ISSUE THREAD

**Issue by danielout** [MyEssentials/MyTown#2]
Receiving the "You cannot access this command" when I attempt to run any /ta commands other than /ta help. The user attempting to run the command has a perms that look like this:
danielout are member of:
   owner (not ranked)
danielout's permissions:
1) mytown.adm.cmd.reload (own)
2) mytown.adm.showlocation (own)
3) mytown.adm.showblocks (own)
   mytown.adm.cmd(|._) (from owner)
   mytown.adm.cmd.setspawn (from admin)
   mytown.adm.cmd.tp (from admin)
   permissions._ (from admin)
   mytown.ecmd(|._) (from player)
   mytown.cmd(|._) (from player)
   mytown.chat(|._) (from player)
   modifyworld._ (from player)

I should note that turning on pex debug does not appear to generate any additional output to the console or to the server log. Also, normal users are unable to allow friends to build on in their towns; friendship works properly but build permissions aren't granted. 

Running: 
FTB Unleashed 1.1.2
MyTown 1.5.1.8
ForgePerms 1.5.1.0
(no MCPC)

**Comment by Torins** [comment]
2:
Friendship works only on plots assigned to a resident. An assistant or mayor must use /mytown assignplot NAME while standing on the chunk you wish to assign.

**Comment by danielout** [comment]
Thanks for the heads up on that one; let me know if I can do anything to help track down the admin problem.

**Comment by jgoett154** [comment]
Since I changed permissions a little, you may have to do this instead
1) mytown.adm.cmd.reload (own)
2) mytown.adm.showlocation (own)
3) mytown.adm.showblocks (own)
mytown.adm.cmd.\* (from owner)
mytown.adm.cmd.setspawn (from admin)
mytown.adm.cmd.tp (from admin)
permissions.\* (from admin)
mytown.ecmd.\* (from player)
mytown.cmd.\* (from player)
mytown.chat.\* (from player)
modifyworld.\* (from player)

Change from using (|._) to ._ It should work without the need to change however, and I have not tested that suggestion just yet, I am downloading forge right now since I always test on MCPC+ myself. As for debug, I haven't touched that since I picked it up from Alpha.

**Comment by Torins** [comment]
if (!canAccess("mytown.adm.cmd.set") || !canAccess("mytown.adm.*")) {
throw noAccess
}

This is just a random /ta command I've read. If all of them are like this, you need mytown.adm.\* to do anything properly at the moment.

LegoBear154, are you sure the || shouldn't be an && ?

**Comment by jgoett154** [comment]
nope, its suppose to be || the mytown.adm.\* will give a person all admin commands without the need for mytown.adm.cmd.set and the others. Since some bukkit permission plugins don't natively support the \* nodes, I added that for the people using those systems.

**Comment by danielout** [comment]
Just tried swapping the perms to "mytown.adm.cmd._" and then "mytown.adm._" and both produced the same results: still no access.

**Comment by Torins** [comment]
The current statement reads: if you don't have A or you don't have B, throw no access.
So you need both nodes... Correct me if I'm wrong reading this.

Edit: I'm not saying "mytown.adm.*" should not give total access. I'm talking about the case where you have only "mytown.adm.cmd.set".

**Comment by jgoett154** [comment]
No, I do believe the or is correct. Because if you had an and, then if would be if you don't have a and you don't have b, throw no access. With the or, you only need one, or the other. It works fine for bukkit based perms so I assumed it would be fine with forgePEx.

**Comment by Torins** [comment]
Exactly. If you don't have a general node (*), and you don't have the explicit node (set), you should not be allowed to use the command.

But if you have one of them, you should be allowed to use it. Am I wrong?
Because at the moment mytown.adm.cmd.set doesn't allow you to use /ta set. You need both perms to be allowed.
So you might aswell remove "mytown.adm.cmd.set" altogether atm, because "mytown.adm.cmd.set" is included in "mytown.adm.*".

**Comment by jgoett154** [comment]
No, the reason for having a general node is to not have to manually give each node to each group/person. If I remove the mytown.adm.cmd.set then people couldn't negate just it. And example of why they are both needed is with PermissionsBukkit. It doesn't directly support the general node (*), so plugins (and in this case mods) have to directly code in support for it.

I should say, I am possibly wrong and that is causing an issue, but to me that shouldn't be.

**Comment by Torins** [comment]
I understand what you're trying to achieve, but I think you're missing my part.

Tell me, given current current code, how would you allow group X to use commands /ta extrares, and only that?

danielout: try the ultimate node: mytown.*

**Comment by jgoett154** [comment]
Oh wait, I think i get what you mean. My bad, idiot me, it is suppose to be &&. Im so sorry Torins. Changing it to && should fix the issue.

**Comment by Torins** [comment]
No problem Lego, just don't ever take personally when I start getting fierce like that :)

**Comment by jgoett154** [comment]
lol, I know. Its been a very long past couple of days :p that same stretch of code gave me crap the other day because I forgot the ! before all of the ones for the \* node :p And yesterday and today I have been working on getting aPerf working in 1.5.x (Not my fault this time!). I will put an update out asap with that fixed.

**Comment by Torins** [comment]
Also: if it's a case only with PermissionsBukkit, wouldn't it be better to elevate it all the way to the CBBridge? You wouldn't have to change it in multiple places inside MyTown.

**Comment by danielout** [comment]
Thanks guys; you rock. Since you do most of your testing with MCPC, I'll make sure I report any other issues I run in to as quickly as I can.

**Comment by Torins** [comment]
Something like canAcess("x.y.z.f.node") {

vault.canAccess(x.y.z.f.node) || vault.canAccess(x.y.z.f._) || vault.canAccess(x.y.z._) ....

**Comment by jgoett154** [comment]
You know what, instead of coding that into every single line, I may try taking a shortcut and just call the canCommandSenderUseCommand(ICommandSender cs) directly since it has the code. And no because from what I can tell, only bukkit pex and permissions2/3 has direct support for the \* node, could be wrong with that as well though. And I could probably break up the node at the dots and loop through all of the possible \* nodes. and no problem at all.

In the time it took me to type this, you both posted a comment :p

**Comment by Torins** [comment]
Yeah, I've been thinking of the same method it seems :) I just think it could be elevated all the way to CBBridge, so other mods (if they ever use forgePerms) won't have to implement simmiliar measures.

In case of bukkit PEx and other systems that work with "_", it'll resolve at the first canAccess, the full node. 
Other systems will be asked in a loop for exact "_" nodes until the permission text becomes an empty string.

**Comment by jgoett154** [comment]
Yea, then just break out of the loop when/if there is a hit on a node. I will do it that way, much less coding in the end really. I over think things at times :)

**Comment by Torins** [comment]
//oftopic begin

I'll have to finally merge your code to my repo and start tinkering again. Stopped after making a working version with what my server needed..
Given that we're still on 1.5.2, do I need to pick the last commit before 1.6.2 and then cherry pick changes from latter commits? Or can I just grab the newest?

danielout: Good to hear everything's resolved :)

**Comment by jgoett154** [comment]
You should be able to grab the newest and only have to change a single set of code (if I remember correctly). The way chat is handled changed between 1.5.x and 1.6.x. Since I found myself doing a lot of redundant copy-paste I made 2 static functions called sendChatToPlayer in the MyTown.jar file at the bottom. Editing those to the required 1.5.x code should let it work out of the box. If you want, I can zip up my local 1.5.2 code and can upload it to Dropbox or something for you to download.

**Comment by danielout** [comment]
Well, let's hope it is resolved; I'll be happy to thoroughly test the fix :smiley: 

//offtopic continues
Now you've made me go and fork because I've been meaning to make myself spend more time coding, and playing around with this mod seems like a good place to start.

**Comment by jgoett154** [comment]
lol, I wish you luck. I will give you a hint on how the protection stuff works. Class.forName function :) http://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#forName(java.lang.String)

Also, Torins, any ideas how we could go about stopping the grab feature of Portalgun inside of towns. Its default key is G. I looked at the code but couldn't think of a way to.

**Comment by Torins** [comment]
^As in, Java is one of the languages where you can simply ignore what the other developer said about accessibility and use everything...

**Comment by jgoett154** [comment]
Exactly! Screw if its private, I will still pull values and call functions! Actually, aPerf uses that for its SpawnLimiter if I remember right. It sets the accessibility of a field to true.

**Comment by Torins** [comment]
As for the dropbox, thanks but no - I want to make a proper github history, so I'll have to discard my changes, pull your code and start applying them again :)

Btw. There's an even deeper api that allows you to actually rewrite other people's code. Nallar uses it to patch other mods so they work with concurrent ticks in TickThreading.
Check it when ya have some free time, it seems very powerful: http://www.javassist.org/

**Comment by jgoett154** [comment]
Ok, sounds good.

Oh nice, thank you for the link, I will bookmark that in case I need it. I always wondered how TickThreading works, just never bothered to look through his source :p Im wanting to say I actually added his patch directly to MyTown a while ago ;)

**Comment by jgoett154** [comment]
Ok, should be all fixed, all changes are pushed to the repos, and dropbox has the jar files there. @danielout here is a download for, what should be this time, the fixed version https://dl.dropboxusercontent.com/u/73334914/MyTown/MyTown-1.5.1.9.jar
