### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by McyD** [MyEssentials/MyTown#52]
We are getting a random crash with MyTown, not sure what is causing it, we have not changed anything on the server in the last few days.

http://pastebin.com/TRzp2j5N

**Comment by jgoett154** [comment]
I don't know what mod is causing that, but some tile entity isn't extending isUseableByPlayer, which MyTown expects to be there. If you can figure out what TE is being right clicked when that happens, I can bring it up with the mod author and see why its happening.

**Comment by McyD** [comment]
Hmm, okay, that is at least a starting point.  The crash from last night only had one player on, so hopefully he can remember what he was doing when it crashed.  I will keep you posted.

**Comment by jgoett154** [comment]
Ok, sounds good! I know EE3 caused the crash before, not sure if it still does.

**Comment by McyD** [comment]
It still does it is the Calcinator, and they say it is an Mytown issue. I quoted your post about: "some tile entity isn't extending isUseableByPlayer".  So hopefully they will get in contact with you or fix the issue on their end.

**Comment by McyD** [comment]
Their response is: "This is pretty much his fault. isUseableByPlayer is implemented in the superclass of EE3's tiles. He should check if any of the superclasses of the tile has this method. I'm not too familiar enough with ASM, but with Reflection it's as easy as changing getDeclaredMethod() to getMethod()."

**Comment by jgoett154** [comment]
Hmm, I thought getDeclaredMethod() would get the superclasses method as well. I will change it though :)

Err... actually, I don't use ASM or Reflection for that...

**Comment by odensc** [comment]
@legobear154 getDeclaredMethod() means get a method that is declared in the class (I.E: public static final derp = "", and derp is not in any of it's superclasses), and not the superclasses. getMethod() means get a method from the superclass if it's not defined in the class, or get a method from the class if it is defined.
But yeah, that seems odd, because I was looking at that line of code and there was no Reflection.

**Comment by jgoett154** [comment]
I think the reason its happening is because TileEE doesn't extend IInventory, but holds the isUseableByPlayer function. So it technically overwrites it, but at the same time it doesn't. Its one of the corner cases of Java I guess. And thank you for the clarification @thesbros. Sometimes the Javadocs don't explain it very well :)

Looks like it will be fixed on EE3's side https://github.com/pahimar/Equivalent-Exchange-3/issues/625 :)

**Comment by jgoett154** [comment]
Closing issue. Pahimar fixed it :) https://github.com/pahimar/Equivalent-Exchange-3/commit/683cde92fb4819f08e2839dde8827ab93a1a1fde
