### ISSUE TITLE
start crash. some debug needed 

### ISSUE THREAD

**Issue by HaoSs07** [MyEssentials/MyTown#9]
http://pastebin.com/rBX6Vf7L

update from bridge 1.1.5 to 1.1.7 and that crash appears at server start.

**Comment by Torins** [comment]
Meeh. Phone is not a good place to do troubleshooting,  but let's try. 
I can't see anything interesting in the log,  then, maybe I missed something, will reread when home. 
Your server timed out. Right after requesting a permission node, right? 
I saw threads being suspended in monitors. At least one was suspended because I believe it tried to access a file. 
So for now. It's this reproduce able?  Does it crash always the same way? Can you make sure nothing is blocking file access? OS file permissions, or os/app having the file opened and thus blocking it? 
That's all I can think of right now

**Comment by HaoSs07** [comment]
is working just fine with 1.1.5 . but with 1.1.7 i had 3 starts with 3 crashes just after the server finish loading (mytown protection is the last one to load, then it runs for 15-30 sec. and crashes ). not sure if is 1.1.7 related or is something else. server is running under gamecp for months with no problems to file permission .

p.s. i don't know what to look for in this kind of error... any tips for debugging ? guide or something ? i hate going to other people to debug stuff. i may not be a dev but any minecraft server owner should know how to debug. :D

**Comment by Torins** [comment]
Not familiar with the provider, but will write later how to connect with eclipse to a server to debug it. At any rate you have to wait for me to get home,  that'll be an hour or so.

**Comment by Torins** [comment]
Okay. Back now. First of all. Any communicator I could reach ya over? Or perhaps irc? I'm always at #NEMServer on Esper.net, and you can join using a web chat at http://www.esper.net/publicirc.php

Asking, because it's more convenient than talking here, especially since I'm not sure where to start with your error.

EDIT:
On debugging. First of all, you need to add the following parameters to the java command you use to start the server
-Xrunjdwp:transport=dt_socket,address=1000,server=y,suspend=n

This will make java listen on port 1000 for incoming connections from your Eclipse. Mind the "suspend=n" part. If you change "n" to "y", java will not begin starting the server until after you connect.

Now, you must prepare Eclipse for connection. Consult Pahimar's Let's Mod series on how to prepare the dev environment in Eclipse, and make sure to add projects for the mods you want to debug. (You might also want to prepare a project for MCPC, because well, it differs from the minecraft-forge project Pahimar creates in his videos).

After that, go to Run > Debug Configurations...  in the new window right click "Remote Java Application" and choose new. Choose a project you want to debug, fill in the host and port. In the source tab you can add other projects too, if you wish.

That's it. You will be able now to place breakpoints in the code in Eclipse, and start the debug (click the arrow near the bug icon and choose the configuration you just made).

Mind you, don't keep the server stopped in a breakpoint for too long, or you risk people getting kicked on timeouts (harmless, but annoying).

**Comment by HaoSs07** [comment]
that is a tone of help :D

**Comment by Torins** [comment]
I've compared the code between 1.1.5 and 1.1.7. There are no differences in code that could result in any sort of crash. And while you're at it, grab https://www.dropbox.com/s/ltq5eyks4g4jgth/ForgePermsCBBridge-1.1.7b.jar which turns all those [Bridge] logs off with a config option.

Still, contact me on irc or tell me where to grab ya, so we can investigate what's causing the timeout and crash.

**Comment by HaoSs07** [comment]
reopen this as it still happening. its not mytown related but any help is good

**Comment by HaoSs07** [comment]
fixed. was a ME AssemblerCluster crashing
